name: Docker Image CI

on:
  push:
    branches: [ docker, master ]
  pull_request:
    branches: [ docker, master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate DockerFile
        run: ./gradlew dockerCreateDockerfile
      - name: Build the Docker image
        run: docker build . --file build/docker/Dockerfile --tag simplebot:$(date +%s)